In [2]:
import pandas as pd

In [3]:
stats= pd.read_csv(r"C:\Users\Owner\Documents\NSS\PYTHON\data\season_stats - season_stats.csv")

In [4]:
stats.head(10)

      28  17  49ers Football Team  27  10  184  230
0   68.0  15  49ers     Cardinals  45  29  144  262
1   78.0  14  49ers      Seahawks  28  16  173  368
2   96.0  13  49ers        Eagles  42  19  146  314
3  117.0  12  49ers      Seahawks  31  13  NaN  209
4  122.0  11  49ers    Buccaneers  27  14  115  333
5  143.0  10  49ers       Jaguars  34   3  144  302
6  207.0   5  49ers       Cowboys  42  10  170  253
7  221.0   4  49ers     Cardinals  35  16  124  283
8  251.0   3  49ers        Giants  30  12  141  310
9  255.0   2  49ers          Rams  30  23  159  206

In [5]:
stats2= stats.copy()

In [6]:
stats2.head(5)

      28  17  49ers Football Team  27  10  184  230
0   68.0  15  49ers     Cardinals  45  29  144  262
1   78.0  14  49ers      Seahawks  28  16  173  368
2   96.0  13  49ers        Eagles  42  19  146  314
3  117.0  12  49ers      Seahawks  31  13  NaN  209
4  122.0  11  49ers    Buccaneers  27  14  115  333

In [7]:
stats3= stats.copy()

In [8]:
stats4= stats.copy()

Claude understanding and interpreting it

In [9]:
import pandas as pd

null_counts = stats.isna().sum()
rows_with_nulls = stats[stats.isna().any(axis=1)].copy()

print('null_counts')
print(null_counts)
print('\nrows_with_any_null', len(rows_with_nulls))
print('\nrows_with_nulls_by_name')
print(rows_with_nulls['name'].value_counts().head(10).to_string())
print('\nrows_with_nulls_by_week')
print(rows_with_nulls['week'].value_counts().head(10).to_string())
print('\nrows_with_nulls_sample')
print(rows_with_nulls.head(10).to_string(index=False))

null_counts
28                1
17                0
49ers             0
Football Team     0
27                0
10                0
184              16
230               0
dtype: int64

rows_with_any_null 17

rows_with_nulls_by_name

KeyError: 'name'

In [ ]:
print('columns:', list(stats.columns))
print('\nhead:')
print(stats.head(5).to_string())
print('\nnull_counts:')
print(stats.isna().sum().to_string())
rows_with_nulls = stats[stats.isna().any(axis=1)].copy()
print('\nrows_with_any_null', len(rows_with_nulls))
print(rows_with_nulls.head(20).to_string())

columns: ['28', '17', '49ers', 'Football Team', '27', '10', '184', '230']

head:
      28  17  49ers Football Team  27  10  184  230
0   68.0  15  49ers     Cardinals  45  29  144  262
1   78.0  14  49ers      Seahawks  28  16  173  368
2   96.0  13  49ers        Eagles  42  19  146  314
3  117.0  12  49ers      Seahawks  31  13  NaN  209
4  122.0  11  49ers    Buccaneers  27  14  115  333

null_counts:
28                1
17                0
49ers             0
Football Team     0
27                0
10                0
184              16
230               0

rows_with_any_null 17
        28    17     49ers  Football Team        27         10       184       230
3    117.0    12     49ers       Seahawks        31         13       NaN       209
14   104.0    12     Bears        Vikings        12         10       NaN       217
40   111.0    12   Broncos         Browns        29         12       NaN       134
78   106.0    12    Chiefs        Raiders        31         17       NaN       298
89   113.0    12     Colts     Buccaneers        27         20       NaN       251
99   119.0    12   Cowboys  Football Team        45         10       NaN       331
110  116.0    12  Dolphins           Jets        34         13       NaN       243
119  107.0    12    Eagles          Bills        37         34       NaN       200
131  115.0    12   Falcons         Saints        24         15       NaN       168
142  109.0    12    Giants       Patriots        10          7       NaN       191
147  110.0    12   Jaguars         Texans        24         21       NaN       364
174    NaN  week      name       opp_name  tm_score  opp_score  rush_yds  pass_yds
179  118.0    12   Packers          Lions        29         22       NaN       268
203  112.0    12      Rams      Cardinals        37         14       NaN       229
212  105.0    12    Ravens       Chargers        20         10       NaN       177
242  114.0    12  Steelers        Bengals        16         10       NaN       278
261  108.0    12    Titans       Panthers        17         10       NaN       185

Stats2: replace nulls with avg of rush_yds

In [ ]:
stats2 = pd.read_csv(
    r"C:\Users\Owner\Documents\NSS\PYTHON\data\season_stats - season_stats.csv",
    header=None,
    names=["team_id", "week", "name", "opp_name", "tm_score", "opp_score", "rush_yds", "pass_yds"]
)

stats2 = stats2[~stats2["week"].astype(str).str.lower().eq("week")].copy()
stats2["rush_yds"] = pd.to_numeric(stats2["rush_yds"], errors="coerce")

rush_mean = stats2["rush_yds"].mean()
stats2["rush_yds"] = stats2["rush_yds"].fillna(rush_mean).astype("int64")

print('stats2 shape:', stats2.shape)
print('nulls after fill:', stats2["rush_yds"].isna().sum())
print('rush_mean:', rush_mean)
print(stats2.head(5).to_string(index=False))

stats2 shape: (272, 8)
nulls after fill: 0
rush_mean: 126.89453125
 team_id week  name      opp_name tm_score opp_score  rush_yds pass_yds
    28.0   17 49ers Football Team       27        10       184      230
    68.0   15 49ers     Cardinals       45        29       144      262
    78.0   14 49ers      Seahawks       28        16       173      368
    96.0   13 49ers        Eagles       42        19       146      314
   117.0   12 49ers      Seahawks       31        13       126      209

In [ ]:
#check to see if there are any nulls in the rush_yds column 
stats2['rush_yds'].isnull().sum()

0

In [ ]:
#check to see if rush_yds is integer type
stats2['rush_yds'].dtype

dtype('int64')

In [ ]:
stats2.head(10)

   team_id week   name       opp_name tm_score opp_score  rush_yds pass_yds
0     28.0   17  49ers  Football Team       27        10       184      230
1     68.0   15  49ers      Cardinals       45        29       144      262
2     78.0   14  49ers       Seahawks       28        16       173      368
3     96.0   13  49ers         Eagles       42        19       146      314
4    117.0   12  49ers       Seahawks       31        13       126      209
5    122.0   11  49ers     Buccaneers       27        14       115      333
6    143.0   10  49ers        Jaguars       34         3       144      302
7    207.0    5  49ers        Cowboys       42        10       170      253
8    221.0    4  49ers      Cardinals       35        16       124      283
9    251.0    3  49ers         Giants       30        12       141      310

Pros of this method
Very simple and quick to implement
Keeps the column numeric and consistent
Works well when missing values are a small fraction of the data
Preserves the overall column distribution better than dropping rows
Cons of this method
It can distort the data because the same average value is inserted into many rows
It may hide true differences between rows
If the missing values are not random, mean imputation can bias your downstream analysis
It is less accurate than more advanced methods like group-based imputation or model-based prediction

Stats3: cleanup with team avarage

In [ ]:
stats3 = pd.read_csv(
    r"C:\Users\Owner\Documents\NSS\PYTHON\data\season_stats - season_stats.csv",
    header=None,
    names=["team_id", "week", "name", "opp_name", "tm_score", "opp_score", "rush_yds", "pass_yds"]
)

stats3 = stats3[~stats3["week"].astype(str).str.lower().eq("week")].copy()
stats3["rush_yds"] = pd.to_numeric(stats3["rush_yds"], errors="coerce")

team_rush_mean = stats3.groupby("name")["rush_yds"].transform("mean")
stats3["rush_yds"] = stats3["rush_yds"].fillna(team_rush_mean).astype("int64")

print('stats3 shape:', stats3.shape)
print('nulls after fill:', stats3["rush_yds"].isna().sum())
print('team-based mean sample:')
print(stats3.groupby('name')['rush_yds'].mean().head(5).to_string())
print(stats3.head(5).to_string(index=False))

stats3 shape: (272, 8)
nulls after fill: 0
team-based mean sample:
name
49ers      153.416667
Bears      178.000000
Bengals    102.666667
Bills      142.909091
Broncos    110.000000
 team_id week  name      opp_name tm_score opp_score  rush_yds pass_yds
    28.0   17 49ers Football Team       27        10       184      230
    68.0   15 49ers     Cardinals       45        29       144      262
    78.0   14 49ers      Seahawks       28        16       173      368
    96.0   13 49ers        Eagles       42        19       146      314
   117.0   12 49ers      Seahawks       31        13       153      209

In [ ]:
#check to see if there are any nulls in the rush_yds column 
stats3['rush_yds'].isnull().sum()
#check to see data type of rush_yds column
stats3['rush_yds'].dtype

dtype('int64')

Pros
Better than a single overall mean for team-based sports data
Keeps the dataset complete and numeric
Preserves more realistic team-level differences
Easy to understand and explain
Cons
Still an estimate, not a true observed value
Can make missing rows appear more “typical” than they really were
If a team has very few games, its average can be unstable
If the missingness is not random, this method can still introduce bias

Stats 4: Replace nulls with predicted vlaues using linear regression
Linear regression- ML method drwas a straight line pattern b/w input vals(name,tm_score...) and target vals(rush_yds)

Pros
Uses multiple features, so it can make better estimates than a single mean
More realistic than filling every missing value with one number
Good as a simple baseline predictive method
Keeps the dataset complete for downstream modeling
Cons
It is still only a prediction, not a true observation
Linear regression is a simple model and may miss nonlinear relationships
Team name as a category is helpful, but the model may still be limited by data size
If the missingness is structured, the model could be biased.

In [ ]:
from sklearn.linear_model import LinearRegression

stats4 = pd.read_csv(
    r"C:\Users\Owner\Documents\NSS\PYTHON\data\season_stats - season_stats.csv",
    header=None,
    names=["team_id", "week", "name", "opp_name", "tm_score", "opp_score", "rush_yds", "pass_yds"]
)

stats4 = stats4[~stats4["week"].astype(str).str.lower().eq("week")].copy()

for col in ["team_id", "week", "tm_score", "opp_score", "rush_yds", "pass_yds"]:
    stats4[col] = pd.to_numeric(stats4[col], errors="coerce")

train = stats4.dropna(subset=["rush_yds"]).copy()
predict_rows = stats4[stats4["rush_yds"].isna()].copy()

X_train = pd.get_dummies(train[["name", "tm_score", "opp_score", "pass_yds"]], columns=["name"])
X_pred = pd.get_dummies(predict_rows[["name", "tm_score", "opp_score", "pass_yds"]], columns=["name"])

X_train, X_pred = X_train.align(X_pred, join="outer", axis=1, fill_value=0)

model = LinearRegression()
model.fit(X_train, train["rush_yds"])
predicted_rush = model.predict(X_pred)

predict_rows["rush_yds"] = predicted_rush.round().astype("int64")
stats4 = pd.concat([train, predict_rows]).sort_index()
stats4["rush_yds"] = stats4["rush_yds"].astype("int64")

print('stats4 shape:', stats4.shape)
print('nulls after fill:', stats4["rush_yds"].isna().sum())
print('predicted sample:')
print(predict_rows.head(5)[["name", "tm_score", "opp_score", "pass_yds", "rush_yds"]].to_string(index=False))

stats4 shape: (272, 8)
nulls after fill: 0
predicted sample:
   name  tm_score  opp_score  pass_yds  rush_yds
  49ers        31         13       209       165
  Bears        12         10       217       138
Broncos        29         12       134       142
 Chiefs        31         17       298       116
  Colts        27         20       251       118

In [ ]:
#check to see if there are any nulls in the rush_yds column
stats4['rush_yds'].isnull().sum()

0

Actual data:

In [ ]:
actual= pd.read_csv(r"C:\Users\Owner\Documents\NSS\PYTHON\data\actual.csv")

In [ ]:
actual.head(5)

   week     name  actual_rush_yds
0    18  Cowboys              131
1    18     Rams              109
2    18   Chiefs              123
3    18  Raiders              129
4    18   Titans              175

In [ ]:
min(stats2['rush_yds'])

29

In [ ]:
filled_rows = stats4[stats4['rush_yds'].notna()].copy()
filled_rows = filled_rows[filled_rows.index.isin(predict_rows.index)]

print('rows that were imputed in stats4:')
print(filled_rows[['name', 'tm_score', 'opp_score', 'pass_yds', 'rush_yds']].to_string(index=False))

rows that were imputed in stats4:
    name  tm_score  opp_score  pass_yds  rush_yds
   49ers        31         13       209       165
   Bears        12         10       217       138
 Broncos        29         12       134       142
  Chiefs        31         17       298       116
   Colts        27         20       251       118
 Cowboys        45         10       331       132
Dolphins        34         13       243       157
  Eagles        37         34       200       165
 Falcons        24         15       168       161
  Giants        10          7       191       114
 Jaguars        24         21       364        82
 Packers        29         22       268       138
    Rams        37         14       229       164
  Ravens        20         10       177       150
Steelers        16         10       278        98
  Titans        17         10       185       137

In [ ]:
stats2_filled = stats2[stats2['rush_yds'].notna()].copy()
stats2_filled = stats2_filled[stats2_filled.index.isin(stats2[stats2['rush_yds'].notna()].index)]

print('rows that were imputed in stats2:')
print(stats2[['name', 'tm_score', 'opp_score', 'pass_yds', 'rush_yds']].head(20).to_string(index=False))

rows that were imputed in stats2:
   name tm_score opp_score pass_yds  rush_yds
  49ers       27        10      230       184
  49ers       45        29      262       144
  49ers       28        16      368       173
  49ers       42        19      314       146
  49ers       31        13      209       126
  49ers       27        14      333       115
  49ers       34         3      302       144
  49ers       42        10      253       170
  49ers       35        16      283       124
  49ers       30        12      310       141
  49ers       30        23      206       159
  49ers       30         7      220       188
  Bears       37        17      268       192
  Bears       27        16      170       250
  Bears       28        13      223       142
  Bears       12        10      217       126
  Bears       16        13      162       133
  Bears       30        12      162       173
  Bears       40        20      282       178
Bengals       31        14      176       183

Mean Absolute Error w/ ChatGPT

In [10]:
stats.head(10)

      28  17  49ers Football Team  27  10  184  230
0   68.0  15  49ers     Cardinals  45  29  144  262
1   78.0  14  49ers      Seahawks  28  16  173  368
2   96.0  13  49ers        Eagles  42  19  146  314
3  117.0  12  49ers      Seahawks  31  13  NaN  209
4  122.0  11  49ers    Buccaneers  27  14  115  333
5  143.0  10  49ers       Jaguars  34   3  144  302
6  207.0   5  49ers       Cowboys  42  10  170  253
7  221.0   4  49ers     Cardinals  35  16  124  283
8  251.0   3  49ers        Giants  30  12  141  310
9  255.0   2  49ers          Rams  30  23  159  206